SET @@SESSION.SQL_LOG_BIN=0;
-- Clean users -- 
DELETE FROM mysql.user
WHERE user NOT IN ('mysql.sys', 'mysqlxsys', 'root') OR host NOT IN ('localhost') ;
-- Config root user --
SET PASSWORD FOR 'root'@'localhost'=PASSWORD('${CONFIG_MARIADB_ROOT_PASS}') ;
GRANT ALL ON *.* TO 'root'@'localhost' WITH GRANT OPTION ;

-- Clean dbs --
DROP DATABASE IF EXISTS test ;

-- Setup default db --
CREATE DATABASE IF NOT EXISTS $CONFIG_MARIADB_DEFAULT_DB_NAME CHARACTER SET $CONFIG_MARIADB_DEFAULT_DB_CHARSET COLLATE $CONFIG_MARIADB_DEFAULT_DB_ENCODING ;
-- Setup default user --
CREATE USER '$CONFIG_MARIADB_DEFAULT_USER'@'%' IDENTIFIED BY '$CONFIG_MARIADB_DEFAULT_PASS' ;
GRANT ALL ON $CONFIG_MARIADB_DEFAULT_DB_NAME.* TO '$CONFIG_MARIADB_DEFAULT_USER'@'%' ;

FLUSH PRIVILEGES ;